# version: '3.8'
services:
  db:
    image: arm64v8/mysql:8.0
    platform: linux/arm64/v8
    restart: always
    environment:
      MYSQL_DATABASE: yi_jia_xiang
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: yi_jia_xiang_user
      MYSQL_PASSWORD: yi_jia_xiang_password_2024
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: yijiaxiang-arm64:0.0.1
    platform: linux/arm64/v8
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: yi_jia_xiang
      DB_USERNAME: yi_jia_xiang_user
      DB_PASSWORD: yi_jia_xiang_password_2024
      CLOUDINARY_URL: cloudinary://697592912781924:20hBk7nMJHVu856JQShTuuDkwyw@daeb3goxf
      CLOUDINARY_CLOUD_NAME: daeb3goxf
      CLOUDINARY_API_KEY: 697592912781924
      CLOUDINARY_API_SECRET: 20hBk7nMJHVu856JQShTuuDkwyw
    ports:
      - "8000:8000"
    working_dir: /var/www

  frontend:
    build: ./frontend
    platform: linux/arm64/v8
    ports:
      - "5180:5173"
    volumes:
      - ./frontend:/app
    working_dir: /app

volumes:
  db_data: 